[technote]
id = "SITCOMTN-162"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-162.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-162"
github_default_branch = "main"
date_created = 2025-06-25T17:43:51Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Miranda R."
name.family = "Gorsuch"
internal_id = "gorsuchmr"
orcid = "https://orcid.org/0000-0002-3135-3824"
[[technote.authors.affiliations]]
name = "Department of Physics"
internal_id = "WisconsinMadison"
address = "University of Wisconsin-Madison, Madison, WI 53706, USA"
